### PR TITLE
feat: adds open-runtimes example for python 3-11

### LINKED ISSUE #110: Feat: Add open-runtime example for `python-3.11` LTS
Hi 👋🏻  @stnguyen90 @Meldiron 

Ref: https://www.python.org/downloads/release/python-3110/
https://github.com/docker-library/python/blob/f04b43cb1775d382587b0446717613fb912225a9/3.11/alpine3.16/Dockerfile

Any thoughts on this adding such? Thanks

### PR DESCRIPTION
**Pull request by afzal442**
Fixes #110

### CODE REVIEW

**Comment by PMohanJ** [comment]
hey @afzal442 the check is failing because two of the [test cases](https://github.com/PMohanJ/open-runtimes/blob/main/tests/Base.php) failed. If you've followed [add-runtime.md](https://github.com/PMohanJ/open-runtimes/blob/main/docs/add-runtime.md#41-creating-your-test-script), there's a typo. Check out this [PR](/open-runtimes/open-runtimes/pull/115)

**Comment by afzal442** [comment]
Yeah! U r right @PMohanJ. I checked that. Thanks for your fix. 😄 GD!

cc @stnguyen90 Any thoughts?

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@afzal442, it seems like the CI jobs are failing because tests are missing.

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by christyjacob4** [comment]
@afzal442 thanks a lot for your contributions during Hacktoberfest 2022! I'll be closing this PR since open runtimes is going to undergo some major refactoring and this example may get outdated soon. I'd urge you to create another PR that conforms to the new syntax. 

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.

**Pull request closed without merging**
