### PR TITLE
Add python ML image

### PR DESCRIPTION
**Pull request by Meldiron**
Python ML image with most needed libarries pre-installed.

### CODE REVIEW

**Comment by gewenyu99** [comment]
Have you tried this with:
- OpenCV
- Pytorch
- Tensorflow
- Mxnet
- [scikit-learn:](https://scikit-learn.org/)
- Pillow (PIL Fork) 
- Theano
- Numpy/Pandas/Matplotlib

These are things that I've found to be commonly used. Although, last time I did ML things at work was 2020 😬

**Comment by thaefeker** [comment]
Is there any progress on this? I have problems with the default alpine images for python in appwrite when I want to use plotly. With the standard python images plotly works in docker without problems

**Comment by gewenyu99** [comment]
> Is there any progress on this? I have problems with the default alpine images for python in appwrite when I want to use plotly. With the standard python images plotly works in docker without problems

Try the Appwrite 1.4 runtime, see if you can install the dependencies under **Build commands**, which lets you write full bash commands now.

**Comment by thaefeker** [comment]
I will try, thank you!

**Comment by loks0n** [comment]
Closing in favour of v3 version 
#231

**Pull request closed without merging**
