### PR TITLE
Fix python build

### PR DESCRIPTION
**Pull request by christyjacob4**

### CODE REVIEW

**Comment by christyjacob4** [comment]
We did a QA and discovered that this approach will not work. 

This is because the build tar.gz has already been created and stored in S3. As a result, our changes to the Dockerfile will not be included in it unless we have a rebuild

**Comment by Meldiron** [comment]
Another possible approach, simply source 2 different folders:

CleanShot 2024-10-17 at 10 46 07@2x

**Comment by Meldiron** [comment]
my approach wont work, you cannot source 2 virtual envs

**Comment by Meldiron** [comment]
Closing this PR, since new ideas dont work, and packaging is already moved to dockerfile (server dependencies not included in build file)

**Pull request closed without merging**
